name: selfmotion
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - ld_impl_linux-64=2.44
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - pip=25.2
  - python=3.10.19
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - build==1.3.0
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.60.1
      - fsspec==2024.6.1
      - intel-openmp==2021.4.0
      - jinja2==3.1.4
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - mkl==2021.4.0
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-cuda==0.0.2
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.0.0
      - pip-tools==7.5.1
      - pyparsing==3.2.5
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - tbb==2021.11.0
      - threadpoolctl==3.6.0
      - tomli==2.3.0
      - torch==2.3.1+cu121
      - torchvision==0.18.1+cu121
      - triton==2.3.1
      - typing-extensions==4.12.2
      - tzdata==2025.2
prefix: /root/miniconda3/envs/selfmotion
